{% set name = "dash-bootstrap-templates" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 666dff73f091e4544337004667ed4c486767a6344695d7cfb2974c660f03aa0e

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - flask <2.3.0
    - werkzeug <2.3.0
    - dash
    - dash-bootstrap-components >=1.0.0
    - dash-core-components >=1.3.1
    - dash-html-components >=1.0.1
    - dash-renderer >=1.2.4
    - dash-table >=4.0.0
    - numpy
    - importlib-resources >=5.1.0
    - importlib-metadata >=3.4.0

test:
  imports:
    - dash_bootstrap_templates
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnnMarieW/dash-bootstrap-templates
  summary: A collection of Plotly figure templates with a Bootstrap theme
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Anselmoo
